version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "eslint-plugin-code-style"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
